In [9]:
import os

import numpy as np

### Test

In [2]:
print(f"Current working directory: {os.getcwd()}")

Current working directory: /home/imahn/Downloads


### Python lists

In [3]:
l = [1, 2, 3, 4]
m = [4, 3, 2, 1]
print(f"Example list: {l}\n\nAnother list: {m}")

Example list: [1, 2, 3, 4]

Another list: [4, 3, 2, 1]


In [4]:
l.append(5)
print(l)

[1, 2, 3, 4, 5]


In [6]:
l.pop(-1)

5

In [72]:
print(l)

[1, 2, 3, 4]


In [74]:
l = [1, 2, 3, 4]
m = [5, 6, 7, 9]
n = l + m
print(n)

[1, 2, 3, 4, 5, 6, 7, 9]


In [87]:
l = [1, 2, 3, 4]
m = [5, 6, 7, 8]
n = l * m
print(n)

TypeError: can't multiply sequence by non-int of type 'list'

In [82]:
l = [1, 2, 3, 4]
m = 2 * l # `l + l`
print(m)

[1, 2, 3, 4, 1, 2, 3, 4]


### Numpy Arrays

#### Array per se

In [66]:
def print_array_info(*args) -> None:
    for arg in args: 
        if type(arg) == np.ndarray: 
            print(f"Array:\n{arg}\nNumber of axes: {arg.ndim}, shape: {arg.shape}, "
                  f"dtype: {arg.dtype}\n\n")
        else: 
            raise ValueError(
                f"Wrong object type: {type(arg)}, expected type "
                "`np.ndarray`"
            )

In [68]:
a = np.array([1., 2., 3., 4.]) # np.array([1, 2, 3, 4])
print_array_info(a)

Array:
[1. 2. 3. 4.]
Number of axes: 1, shape: (4,), dtype: float64




In [47]:
a2 = np.array([1., 2, 3, 4])
print_array_info(a2)

Array:
[1. 2. 3. 4.]
Number of axes: 1, shape: (4,), dtype: float64


In [22]:
b = np.array([l])
print_array_info(b)

Array: [[1 2 3 4]], number of axes: 2, shape: (1, 4)


In [23]:
c = np.array([[l]])
print_array_info(c)

Array: [[[1 2 3 4]]], number of axes: 3, shape: (1, 1, 4)


In [29]:
d = np.array([[1, 2, 4, 5], [6, 7, 8, 9], [10, 11, 12, 98]])
print_array_info(d)

Array:
[[ 1  2  4  5]
 [ 6  7  8  9]
 [10 11 12 98]]
Number of axes: 2, shape: (3, 4)


#### Array Manipulations

In [79]:
# a = np.random.rand(2, 2)
# b = np.random.rand(2, 2)
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 9])
print_array_info(a, b)

c = a + b
print_array_info(c)

Array:
[1 2 3 4]
Number of axes: 1, shape: (4,), dtype: int64


Array:
[5 6 7 9]
Number of axes: 1, shape: (4,), dtype: int64


Array:
[ 6  8 10 13]
Number of axes: 1, shape: (4,), dtype: int64




In [86]:
c = np.array([1, 2, 3, 4])
d = np.array([5, 6, 7, 8])
e = c * d
print_array_info(c, d, e)

Array:
[1 2 3 4]
Number of axes: 1, shape: (4,), dtype: int64


Array:
[5 6 7 8]
Number of axes: 1, shape: (4,), dtype: int64


Array:
[ 5 12 21 32]
Number of axes: 1, shape: (4,), dtype: int64




In [90]:
c = np.array([1, 2, 3, 4])
d = 2 * c # `np.array([2, 2, 2, 2]) * np.array([1, 2, 3, 4])`
print_array_info(d)

Array:
[2 4 6 8]
Number of axes: 1, shape: (4,), dtype: int64




In [93]:
# This will not work, expected
c = np.array([1, 2, 3, 4])
d = np.array([2, 3])
e = d * c
print_array_info(e)

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

### Sets

In [12]:
s = set(l)
t = set(m)
print(f"Example set: {s}\n\nAnother set: {t}")

Example set: {1, 2, 3, 4}

Another set: {1, 2, 3, 4}
